"use client";
import {useEffect,useState} from "react";
import {supabase} from "../lib/supabase";
type Metrics={total_customers:number;active_customers:number;trial_customers:number;mrr:number;arr:number;new_customers_this_month:number;marketing_spend_this_month:number;leads_this_month:number;conversions_this_month:number;cac_this_month:number|null;forecast_data_status:string};
export default function Home(){const [loading,setLoading]=useState(true);const [metrics,setMetrics]=useState<Metrics|null>(null);const [error,setError]=useState("");
useEffect(()=>{(async()=>{const s=supabase();const {data:{user}}=await s.auth.getUser();if(!user){location.href="/login";return}const {data,error}=await s.rpc("get_admin_dashboard_summary");if(error){setError(error.message)}else{setMetrics(data?.[0]??null)}setLoading(false)})()},[]);
const logout=async()=>{await supabase().auth.signOut();location.href="/login"};
return <div className="shell"><aside className="sidebar"><div className="brand">Vyapar Analytics</div><nav className="nav"><a className="active" href="/">Dashboard</a><a href="/customers">Customers</a><a href="/finance">Finance & Growth</a><a href="/organization">Organization</a><a href="/settings">Settings & Platform</a></nav></aside><main className="main"><div className="top"><div><div className="title">Admin Dashboard</div><div className="muted">Business and platform control center</div></div><button className="button" style={{width:"auto",padding:"9px 16px"}} onClick={logout}>Sign out</button></div>{loading?<div className="card">Loading dashboard...</div>:error?<div className="notice">{error}</div>:metrics&&<><div className="grid"><Metric label="MRR" value={money(metrics.mrr)}/><Metric label="ARR" value={money(metrics.arr)}/><Metric label="Total Customers" value={metrics.total_customers.toLocaleString()}/><Metric label="Active Customers" value={metrics.active_customers.toLocaleString()}/><Metric label="Trial Customers" value={metrics.trial_customers.toLocaleString()}/><Metric label="New This Month" value={metrics.new_customers_this_month.toLocaleString()}/><Metric label="Ad Spend This Month" value={money(metrics.marketing_spend_this_month)}/><Metric label="CAC This Month" value={metrics.cac_this_month==null?"—":money(metrics.cac_this_month)}/></div><div className="section"><div className="sectionTitle">Growth & Forecast</div><div className="card"><div className="muted">Forecast data status</div><div className="value">{metrics.forecast_data_status==="available"?"Ready":"Insufficient history"}</div><p className="muted">Forecasts will use actual customer and revenue history. No synthetic business metrics are generated.</p></div></div></>}</main></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="card"><div className="label">{label}</div><div className="value">{value}</div></div>}
function money(v:number){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v||0)}