"use client";
import {useEffect,useState} from "react";
import AdminShell from "../../components/admin-shell";
import {supabase} from "../../lib/supabase";
type Growth={month:string;new_customers:number}; type Marketing={month:string;ad_spend:number;leads:number;conversions:number;cac:number|null}; type Plan={id:string;code:string;name:string;monthly_price:number;annual_price:number;currency_code:string;is_active:boolean};
const money=(v:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(v||0));
export default function Finance(){
 const [growth,setGrowth]=useState<Growth[]>([]),[marketing,setMarketing]=useState<Marketing[]>([]),[plans,setPlans]=useState<Plan[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);const s=supabase();const [g,m,p]=await Promise.all([s.rpc("get_admin_customer_growth"),s.rpc("get_admin_marketing_monthly"),s.from("subscription_plans").select("id,code,name,monthly_price,annual_price,currency_code,is_active").order("monthly_price")]);if(g.error||m.error||p.error)setError(g.error?.message||m.error?.message||p.error?.message||"Unable to load");else{setGrowth(g.data||[]);setMarketing(m.data||[]);setPlans(p.data||[])}setLoading(false)};
 useEffect(()=>{load()},[]);
 const totalSpend=marketing.reduce((a,x)=>a+Number(x.ad_spend||0),0),totalLeads=marketing.reduce((a,x)=>a+Number(x.leads||0),0),totalConv=marketing.reduce((a,x)=>a+Number(x.conversions||0),0);
 return <AdminShell active="/finance">{error&&<div className="notice">{error}</div>}{loading?<div className="card">Loading finance...</div>:<><div className="statsRow"><div className="card"><div className="label">12M New Customers</div><div className="value">{growth.reduce((a,x)=>a+Number(x.new_customers||0),0)}</div></div><div className="card"><div className="label">12M Ad Spend</div><div className="value">{money(totalSpend)}</div></div><div className="card"><div className="label">12M Leads</div><div className="value">{totalLeads}</div></div><div className="card"><div className="label">12M Conversions</div><div className="value">{totalConv}</div></div></div>
 <div className="twoCol"><div className="card tableCard"><div className="sectionTitle">Customer Growth</div><table><thead><tr><th>Month</th><th>New Customers</th></tr></thead><tbody>{growth.map(x=><tr key={x.month}><td>{new Date(x.month).toLocaleDateString("en-IN",{month:"short",year:"numeric"})}</td><td>{x.new_customers}</td></tr>)}</tbody></table></div>
 <div className="card tableCard"><div className="sectionTitle">Marketing Performance</div><table><thead><tr><th>Month</th><th>Spend</th><th>Leads</th><th>Conv.</th><th>CAC</th></tr></thead><tbody>{marketing.map(x=><tr key={x.month}><td>{new Date(x.month).toLocaleDateString("en-IN",{month:"short",year:"numeric"})}</td><td>{money(x.ad_spend)}</td><td>{x.leads}</td><td>{x.conversions}</td><td>{x.cac==null?"—":money(x.cac)}</td></tr>)}</tbody></table></div></div>
 <div className="card tableCard"><div className="sectionTitle">Subscription Plans</div><table><thead><tr><th>Plan</th><th>Monthly</th><th>Annual</th><th>Status</th></tr></thead><tbody>{plans.map(p=><tr key={p.id}><td><strong>{p.name}</strong><div className="muted">{p.code}</div></td><td>{money(p.monthly_price)}</td><td>{money(p.annual_price)}</td><td><span className={p.is_active?"badge good":"badge"}>{p.is_active?"ACTIVE":"INACTIVE"}</span></td></tr>)}</tbody></table></div></>}</AdminShell>
}