"use client";
import {useEffect,useState} from "react";
import AdminShell from "../../components/admin-shell";
import {supabase} from "../../lib/supabase";
type Admin={id:string;user_id:string;display_name:string;status:string;role_id:string|null;department_id:string|null;created_at:string;role?:{code:string;name:string}|null;department?:{name:string}|null};
type Role={id:string;code:string;name:string;description:string|null;is_active:boolean}; type Dept={id:string;name:string;is_active:boolean};
export default function Organization(){
 const [admins,setAdmins]=useState<Admin[]>([]),[roles,setRoles]=useState<Role[]>([]),[depts,setDepts]=useState<Dept[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);const s=supabase();const [a,r,d]=await Promise.all([s.from("admin_users").select("id,user_id,display_name,status,role_id,department_id,created_at,admin_roles(code,name),admin_departments(name)").order("created_at"),s.from("admin_roles").select("id,code,name,description,is_active").order("name"),s.from("admin_departments").select("id,name,is_active").order("name")]);if(a.error||r.error||d.error)setError(a.error?.message||r.error?.message||d.error?.message||"Unable to load");else{setAdmins((a.data||[]).map((x:any)=>({...x,role:x.admin_roles,department:x.admin_departments})));setRoles(r.data||[]);setDepts(d.data||[])}setLoading(false)};
 useEffect(()=>{load()},[]);
 const toggle=async(a:Admin)=>{const next=a.status==="active"?"suspended":"active";const {error}=await supabase().from("admin_users").update({status:next}).eq("id",a.id);if(!error)setAdmins(x=>x.map(v=>v.id===a.id?{...v,status:next}:v))};
 return <AdminShell active="/organization">{error&&<div className="notice">{error}</div>}{loading?<div className="card">Loading organization...</div>:<><div className="statsRow"><div className="card"><div className="label">Admin Users</div><div className="value">{admins.length}</div></div><div className="card"><div className="label">Active Admins</div><div className="value">{admins.filter(x=>x.status==="active").length}</div></div><div className="card"><div className="label">Roles</div><div className="value">{roles.length}</div></div><div className="card"><div className="label">Departments</div><div className="value">{depts.length}</div></div></div>
 <div className="card tableCard"><div className="sectionTitle">Admin Team</div><table><thead><tr><th>Name</th><th>Role</th><th>Department</th><th>Status</th><th></th></tr></thead><tbody>{admins.map(a=><tr key={a.id}><td><strong>{a.display_name}</strong><div className="muted">{a.user_id}</div></td><td>{a.role?.name||"Unassigned"}</td><td>{a.department?.name||"Unassigned"}</td><td><span className={a.status==="active"?"badge good":"badge"}>{a.status.toUpperCase()}</span></td><td><button className="linkButton" onClick={()=>toggle(a)}>{a.status==="active"?"Suspend":"Activate"}</button></td></tr>)}</tbody></table></div>
 <div className="twoCol"><div className="card tableCard"><div className="sectionTitle">Roles</div><table><thead><tr><th>Code</th><th>Name</th><th>Status</th></tr></thead><tbody>{roles.map(r=><tr key={r.id}><td>{r.code}</td><td>{r.name}</td><td>{r.is_active?"Active":"Inactive"}</td></tr>)}</tbody></table></div><div className="card tableCard"><div className="sectionTitle">Departments</div><table><thead><tr><th>Name</th><th>Status</th></tr></thead><tbody>{depts.map(d=><tr key={d.id}><td>{d.name}</td><td>{d.is_active?"Active":"Inactive"}</td></tr>)}</tbody></table></div></div></>}</AdminShell>
}