"use client";
import {useEffect,useState} from "react";
import AdminShell from "../../components/admin-shell";
import {supabase} from "../../lib/supabase";
import {notifyAdminRefreshComplete,useAdminRefresh} from "../../lib/admin-refresh";
type Setting={id:string;key:string;value:any;updated_at:string}; type Perm={id:string;code:string;module:string;action:string}; type Audit={id:string;action:string;entity_type:string|null;entity_id:string|null;created_at:string};
export default function Settings(){
 const [settings,setSettings]=useState<Setting[]>([]),[perms,setPerms]=useState<Perm[]>([]),[audits,setAudits]=useState<Audit[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async(showLoading=true)=>{if(showLoading)setLoading(true);const s=supabase();const [a,p,l]=await Promise.all([s.from("platform_settings").select("id,key,value,updated_at").order("key"),s.from("admin_permissions").select("id,code,module,action").order("module,code"),s.from("admin_audit_logs").select("id,action,entity_type,entity_id,created_at").order("created_at",{ascending:false}).limit(25)]);if(a.error||p.error||l.error)setError(a.error?.message||p.error?.message||l.error?.message||"Unable to load");else{setSettings(a.data||[]);setPerms(p.data||[]);setAudits(l.data||[])}setLoading(false);notifyAdminRefreshComplete()};
 useEffect(()=>{load()},[]);
 const save=async(s:Setting)=>{const {error}=await supabase().from("platform_settings").update({value:s.value}).eq("id",s.id);if(error)setError(error.message);else setSettings(x=>x.map(v=>v.id===s.id?{...v,updated_at:new Date().toISOString()}:v))};
 return <AdminShell active="/settings">{error&&<div className="notice">{error}</div>}{loading?<div className="card">Loading settings...</div>:<><div className="statsRow"><div className="card"><div className="label">Platform Settings</div><div className="value">{settings.length}</div></div><div className="card"><div className="label">Permissions</div><div className="value">{perms.length}</div></div><div className="card"><div className="label">Audit Events Shown</div><div className="value">{audits.length}</div></div></div>
 <div className="card tableCard"><div className="sectionTitle">Platform Settings</div>{settings.length?<table><thead><tr><th>Key</th><th>Value</th><th>Updated</th><th></th></tr></thead><tbody>{settings.map(s=><tr key={s.id}><td><strong>{s.key}</strong></td><td><input className="input inlineInput" value={JSON.stringify(s.value)} onChange={e=>{try{const v=JSON.parse(e.target.value);setSettings(x=>x.map(z=>z.id===s.id?{...z,value:v}:z))}catch{}}}/></td><td>{new Date(s.updated_at).toLocaleString("en-IN")}</td><td><button className="linkButton" onClick={()=>save(s)}>Save</button></td></tr>)}</tbody></table>:<div className="empty">No platform settings configured yet.</div>}</div>
 <div className="twoCol"><div className="card tableCard"><div className="sectionTitle">Permissions</div><table><thead><tr><th>Code</th><th>Module</th><th>Action</th></tr></thead><tbody>{perms.map(p=><tr key={p.id}><td>{p.code}</td><td>{p.module}</td><td>{p.action}</td></tr>)}</tbody></table></div><div className="card tableCard"><div className="sectionTitle">Recent Admin Audit</div>{audits.length?<table><thead><tr><th>Action</th><th>Entity</th><th>When</th></tr></thead><tbody>{audits.map(a=><tr key={a.id}><td>{a.action}</td><td>{a.entity_type||"—"}</td><td>{new Date(a.created_at).toLocaleString("en-IN")}</td></tr>)}</tbody></table>:<div className="empty">No admin audit events yet.</div>}</div></div></>}</AdminShell>
}