"use client";
import {useEffect,useMemo,useState} from "react";
import AdminShell from "../../components/admin-shell";
import {supabase} from "../../lib/supabase";
type Customer={id:string;name:string;legal_name:string|null;business_type:string|null;industry:string|null;email:string|null;phone:string|null;is_active:boolean;lifecycle_status:"ACTIVE"|"SUSPENDED"|"OFFBOARDED";created_at:string};
type Issue={id:string;business_id:string|null;title:string;priority:string;status:string;created_at:string};

export default function Customers(){
 const [rows,setRows]=useState<Customer[]>([]),[issues,setIssues]=useState<Issue[]>([]),[q,setQ]=useState(""),[filter,setFilter]=useState("ALL"),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");const s=supabase();const [b,i]=await Promise.all([
  s.from("businesses").select("id,name,legal_name,business_type,industry,email,phone,is_active,lifecycle_status,created_at").order("created_at",{ascending:false}),
  s.from("support_issues").select("id,business_id,title,priority,status,created_at").order("created_at",{ascending:false}).limit(20)
 ]);if(b.error||i.error)setError(b.error?.message||i.error?.message||"Unable to load customer data");else{setRows(b.data||[]);setIssues(i.data||[])}setLoading(false)};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>rows.filter(r=>(filter==="ALL"||r.lifecycle_status===filter)&&(!q||[r.name,r.legal_name,r.email,r.phone,r.industry].filter(Boolean).join(" ").toLowerCase().includes(q.toLowerCase()))),[rows,q,filter]);
 const setStatus=async(r:Customer,status:Customer["lifecycle_status"])=>{const reason=window.prompt("Reason (optional):")??null;const {data,error}=await supabase().rpc("admin_set_customer_lifecycle",{p_business_id:r.id,p_status:status,p_reason:reason});if(error){setError(error.message);return}setRows(x=>x.map(v=>v.id===r.id?{...v,lifecycle_status:status,is_active:status==="ACTIVE"}:v));};
 const active=rows.filter(x=>x.lifecycle_status==="ACTIVE").length, suspended=rows.filter(x=>x.lifecycle_status==="SUSPENDED").length, offboarded=rows.filter(x=>x.lifecycle_status==="OFFBOARDED").length, openIssues=issues.filter(x=>["open","in_progress"].includes(x.status)).length;
 return <AdminShell active="/customers">
  <div className="toolbar"><input className="input search" placeholder="Search business, email, phone..." value={q} onChange={e=>setQ(e.target.value)}/><select className="select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">All</option><option value="ACTIVE">Active</option><option value="SUSPENDED">Suspended</option><option value="OFFBOARDED">Offboarded</option></select><button className="button small" onClick={load}>Refresh</button></div>
  {error&&<div className="notice">{error}</div>}
  <div className="statsRow"><div className="card"><div className="label">Customers</div><div className="value">{rows.length}</div></div><div className="card"><div className="label">Active</div><div className="value">{active}</div></div><div className="card"><div className="label">Suspended</div><div className="value">{suspended}</div></div><div className="card"><div className="label">Open Issues</div><div className="value">{openIssues}</div></div></div>
  <div className="card tableCard"><div className="sectionTitle">Customer Accounts</div>{loading?<div className="muted">Loading...</div>:<div className="tableWrap"><table><thead><tr><th>Business</th><th>Contact</th><th>Type</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><a className="customerLink" href={"/customers/"+r.id}><strong>{r.name}</strong></a><div className="muted">{r.industry||r.legal_name||"—"}</div></td><td>{r.email||"—"}<div className="muted">{r.phone||"—"}</div></td><td>{r.business_type||"—"}</td><td><span className={r.lifecycle_status==="ACTIVE"?"badge good":r.lifecycle_status==="SUSPENDED"?"badge warningBadge":"badge"}>{r.lifecycle_status}</span></td><td>{new Date(r.created_at).toLocaleDateString("en-IN")}</td><td><div className="actionButtons"><a className="linkButton" href={"/customers/"+r.id}>View</a>{r.lifecycle_status!=="ACTIVE"&&<button className="linkButton" onClick={()=>setStatus(r,"ACTIVE")}>Activate</button>}{r.lifecycle_status==="ACTIVE"&&<button className="linkButton" onClick={()=>setStatus(r,"SUSPENDED")}>Suspend</button>}{r.lifecycle_status!=="OFFBOARDED"&&<button className="dangerLink" onClick={()=>setStatus(r,"OFFBOARDED")}>Offboard</button>}</div></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">No customers match the current filter.</div>}</div>}</div>
  <div className="card tableCard"><div className="sectionTitle">Recent Support Issues</div>{issues.length?<div className="tableWrap"><table><thead><tr><th>Issue</th><th>Priority</th><th>Status</th><th>Created</th></tr></thead><tbody>{issues.map(i=><tr key={i.id}><td>{i.title}</td><td>{i.priority}</td><td>{i.status}</td><td>{new Date(i.created_at).toLocaleDateString("en-IN")}</td></tr>)}</tbody></table></div>:<div className="empty">No support issues recorded.</div>}</div>
 </AdminShell>
}