"use client";
import {useEffect,useMemo,useState} from "react";
import AdminShell from "../../components/admin-shell";
import {supabase} from "../../lib/supabase";

type Customer={id:string;name:string;legal_name:string|null;business_type:string|null;industry:string|null;email:string|null;phone:string|null;is_active:boolean;created_at:string};
type Issue={id:string;business_id:string|null;title:string;priority:string;status:string;created_at:string};

export default function Customers(){
 const [rows,setRows]=useState<Customer[]>([]),[issues,setIssues]=useState<Issue[]>([]),[q,setQ]=useState(""),[filter,setFilter]=useState("all"),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);const s=supabase();const [b,i]=await Promise.all([s.from("businesses").select("id,name,legal_name,business_type,industry,email,phone,is_active,created_at").order("created_at",{ascending:false}),s.from("support_issues").select("id,business_id,title,priority,status,created_at").order("created_at",{ascending:false}).limit(20)]);if(b.error||i.error)setError(b.error?.message||i.error?.message||"Unable to load");else{setRows(b.data||[]);setIssues(i.data||[])}setLoading(false)};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>rows.filter(r=>(filter==="all"||filter==="active"&&r.is_active||filter==="inactive"&&!r.is_active)&&(!q||[r.name,r.legal_name,r.email,r.phone,r.industry].filter(Boolean).join(" ").toLowerCase().includes(q.toLowerCase()))),[rows,q,filter]);
 const toggle=async(r:Customer)=>{const next=!r.is_active;const {error}=await supabase().from("businesses").update({is_active:next}).eq("id",r.id);if(!error)setRows(x=>x.map(v=>v.id===r.id?{...v,is_active:next}:v))};
 return <AdminShell active="/customers"><div className="toolbar"><input className="input search" placeholder="Search business, email, phone..." value={q} onChange={e=>setQ(e.target.value)}/><select className="select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All</option><option value="active">Active</option><option value="inactive">Inactive</option></select><button className="button small" onClick={load}>Refresh</button></div>
 {error&&<div className="notice">{error}</div>}<div className="statsRow"><div className="card"><div className="label">Customers</div><div className="value">{rows.length}</div></div><div className="card"><div className="label">Active</div><div className="value">{rows.filter(x=>x.is_active).length}</div></div><div className="card"><div className="label">Open Issues</div><div className="value">{issues.filter(x=>x.status==="open"||x.status==="in_progress").length}</div></div></div>
 <div className="card tableCard"><div className="sectionTitle">Customer Accounts</div>{loading?<div className="muted">Loading...</div>:<div className="tableWrap"><table><thead><tr><th>Business</th><th>Contact</th><th>Type</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><strong>{r.name}</strong><div className="muted">{r.industry||r.legal_name||"—"}</div></td><td>{r.email||"—"}<div className="muted">{r.phone||"—"}</div></td><td>{r.business_type||"—"}</td><td><span className={r.is_active?"badge good":"badge"}>{r.is_active?"ACTIVE":"INACTIVE"}</span></td><td>{new Date(r.created_at).toLocaleDateString("en-IN")}</td><td><button className="linkButton" onClick={()=>toggle(r)}>{r.is_active?"Deactivate":"Activate"}</button></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">No customers match the current filter.</div>}</div>}</div>
 <div className="card tableCard"><div className="sectionTitle">Recent Support Issues</div>{issues.length?<div className="tableWrap"><table><thead><tr><th>Issue</th><th>Priority</th><th>Status</th><th>Created</th></tr></thead><tbody>{issues.map(i=><tr key={i.id}><td>{i.title}</td><td>{i.priority}</td><td>{i.status}</td><td>{new Date(i.created_at).toLocaleDateString("en-IN")}</td></tr>)}</tbody></table></div>:<div className="empty">No support issues recorded.</div>}</div></AdminShell>
}