-- Sprint 1 Admin mutation boundary. Production-applied migration.
begin;

-- Billing / payments
create or replace function public.admin_update_billing_company_profile(p_id uuid,p_payload jsonb,p_reason text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare old_row jsonb; new_row jsonb;
begin
 if not public.has_admin_permission('payments.manage') then raise exception 'payments.manage permission required'; end if;
 if coalesce(trim(p_reason),'')='' then raise exception 'Reason is required'; end if;
 select to_jsonb(b) into old_row from public.billing_company_profile b where b.id=p_id;
 if old_row is null then raise exception 'Billing company profile not found'; end if;
 update public.billing_company_profile set legal_name=coalesce(p_payload->>'legal_name',legal_name),trade_name=p_payload->>'trade_name',pan=p_payload->>'pan',gstin=p_payload->>'gstin',cin=p_payload->>'cin',billing_email=p_payload->>'billing_email',billing_phone=p_payload->>'billing_phone',website=p_payload->>'website',address_line1=p_payload->>'address_line1',address_line2=p_payload->>'address_line2',city=p_payload->>'city',state=p_payload->>'state',postal_code=p_payload->>'postal_code',country_code=coalesce(p_payload->>'country_code',country_code),invoice_prefix=coalesce(p_payload->>'invoice_prefix',invoice_prefix),invoice_terms=coalesce(p_payload->>'invoice_terms',invoice_terms),support_email=p_payload->>'support_email',support_phone=p_payload->>'support_phone',updated_at=now() where id=p_id returning to_jsonb(billing_company_profile) into new_row;
 perform public.admin_append_audit('BILLING_COMPANY_PROFILE_UPDATED','billing_company_profile',p_id,old_row,new_row,p_reason); return new_row;
end $$;

create or replace function public.admin_upsert_payment_method(p_id uuid,p_payload jsonb,p_reason text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare old_row jsonb; new_row jsonb; v_id uuid;
begin
 if not public.has_admin_permission('payments.manage') then raise exception 'payments.manage permission required'; end if;
 if coalesce(trim(p_reason),'')='' then raise exception 'Reason is required'; end if;
 if p_id is null then
  insert into public.billing_payment_methods(code,display_name,method_type,provider,is_active,is_default,beneficiary_name,bank_name,ifsc_code,branch_name,upi_id,merchant_account_id,public_key,checkout_url,settlement_currency,instructions,account_number_last4,account_number_vault_id,gateway_secret_vault_id,webhook_secret_vault_id)
  values(p_payload->>'code',p_payload->>'display_name',p_payload->>'method_type',nullif(p_payload->>'provider',''),coalesce((p_payload->>'is_active')::boolean,true),coalesce((p_payload->>'is_default')::boolean,false),p_payload->>'beneficiary_name',p_payload->>'bank_name',p_payload->>'ifsc_code',p_payload->>'branch_name',p_payload->>'upi_id',p_payload->>'merchant_account_id',p_payload->>'public_key',p_payload->>'checkout_url',coalesce(p_payload->>'settlement_currency','INR'),p_payload->>'instructions',nullif(p_payload->>'account_number_last4',''),nullif(p_payload->>'account_number_vault_id','')::uuid,nullif(p_payload->>'gateway_secret_vault_id','')::uuid,nullif(p_payload->>'webhook_secret_vault_id','')::uuid)
  returning id,to_jsonb(billing_payment_methods) into v_id,new_row;
 else
  select to_jsonb(b) into old_row from public.billing_payment_methods b where b.id=p_id;
  update public.billing_payment_methods set code=coalesce(p_payload->>'code',code),display_name=coalesce(p_payload->>'display_name',display_name),method_type=coalesce(p_payload->>'method_type',method_type),provider=p_payload->>'provider',is_active=coalesce((p_payload->>'is_active')::boolean,is_active),is_default=coalesce((p_payload->>'is_default')::boolean,is_default),beneficiary_name=p_payload->>'beneficiary_name',bank_name=p_payload->>'bank_name',ifsc_code=p_payload->>'ifsc_code',branch_name=p_payload->>'branch_name',upi_id=p_payload->>'upi_id',merchant_account_id=p_payload->>'merchant_account_id',public_key=p_payload->>'public_key',checkout_url=p_payload->>'checkout_url',settlement_currency=coalesce(p_payload->>'settlement_currency',settlement_currency),instructions=p_payload->>'instructions',account_number_last4=p_payload->>'account_number_last4',account_number_vault_id=nullif(p_payload->>'account_number_vault_id','')::uuid,gateway_secret_vault_id=nullif(p_payload->>'gateway_secret_vault_id','')::uuid,webhook_secret_vault_id=nullif(p_payload->>'webhook_secret_vault_id','')::uuid,updated_at=now() where id=p_id returning id,to_jsonb(billing_payment_methods) into v_id,new_row;
 end if;
 if coalesce((p_payload->>'is_default')::boolean,false) then update public.billing_payment_methods set is_default=false,updated_at=now() where id<>v_id; end if;
 perform public.admin_append_audit(case when old_row is null then 'BILLING_PAYMENT_METHOD_CREATED' else 'BILLING_PAYMENT_METHOD_UPDATED' end,'billing_payment_methods',v_id,old_row,new_row,p_reason); return new_row;
end $$;

-- Subscription/platform mutation RPCs use the same pattern: permission check, mandatory reason, mutation, atomic audit.
create or replace function public.admin_update_subscription_billing_settings(p_id uuid,p_payload jsonb,p_reason text) returns jsonb language plpgsql security definer set search_path=public as $$ declare o jsonb;n jsonb; begin if not public.has_admin_permission('subscriptions.manage') then raise exception 'subscriptions.manage permission required';end if;if trim(coalesce(p_reason,''))='' then raise exception 'Reason is required';end if;select to_jsonb(x) into o from public.subscription_billing_settings x where id=p_id;update public.subscription_billing_settings set default_trial_days=coalesce((p_payload->>'default_trial_days')::int,default_trial_days),grace_period_days=coalesce((p_payload->>'grace_period_days')::int,grace_period_days),invoice_due_days=coalesce((p_payload->>'invoice_due_days')::int,invoice_due_days),auto_renew=coalesce((p_payload->>'auto_renew')::boolean,auto_renew),proration_mode=coalesce(p_payload->>'proration_mode',proration_mode),cancellation_mode=coalesce(p_payload->>'cancellation_mode',cancellation_mode),failed_payment_action=coalesce(p_payload->>'failed_payment_action',failed_payment_action),dunning_enabled=coalesce((p_payload->>'dunning_enabled')::boolean,dunning_enabled),tax_mode=coalesce(p_payload->>'tax_mode',tax_mode),billing_anchor=coalesce(p_payload->>'billing_anchor',billing_anchor),default_currency=coalesce(p_payload->>'default_currency',default_currency),payment_provider=p_payload->>'payment_provider',payment_collection_mode=coalesce(p_payload->>'payment_collection_mode',payment_collection_mode),default_payment_method_id=nullif(p_payload->>'default_payment_method_id','')::uuid,invoice_prefix=coalesce(p_payload->>'invoice_prefix',invoice_prefix),invoice_terms=coalesce(p_payload->>'invoice_terms',invoice_terms),updated_at=now() where id=p_id returning to_jsonb(subscription_billing_settings) into n;perform public.admin_append_audit('SUBSCRIPTION_BILLING_SETTINGS_UPDATED','subscription_billing_settings',p_id,o,n,p_reason);return n;end $$;

create or replace function public.admin_update_business_subscription(p_id uuid,p_patch jsonb,p_reason text) returns jsonb language plpgsql security definer set search_path=public as $$ declare o jsonb;n jsonb;begin if not public.has_admin_permission('subscriptions.manage') then raise exception 'subscriptions.manage permission required';end if;if trim(coalesce(p_reason,''))='' then raise exception 'Reason is required';end if;select to_jsonb(x) into o from public.business_subscriptions x where id=p_id;update public.business_subscriptions set status=coalesce(p_patch->>'status',status),cancel_at_period_end=coalesce((p_patch->>'cancel_at_period_end')::boolean,cancel_at_period_end),updated_at=now() where id=p_id returning to_jsonb(business_subscriptions) into n;perform public.admin_append_audit('BUSINESS_SUBSCRIPTION_UPDATED','business_subscription',p_id,o,n,p_reason);return n;end $$;

create or replace function public.admin_update_platform_setting(p_id uuid,p_value jsonb,p_reason text) returns jsonb language plpgsql security definer set search_path=public as $$ declare o jsonb;n jsonb;begin if not public.has_admin_permission('platform.manage') then raise exception 'platform.manage permission required';end if;if trim(coalesce(p_reason,''))='' then raise exception 'Reason is required';end if;select to_jsonb(x) into o from public.platform_settings x where id=p_id;if o->>'key'='max_fixed_discount' then raise exception 'Use admin_set_fixed_discount_ceiling';end if;update public.platform_settings set value=p_value,updated_at=now() where id=p_id returning to_jsonb(platform_settings) into n;perform public.admin_append_audit('PLATFORM_SETTING_UPDATED','platform_setting',p_id,o,n,p_reason);return n;end $$;

create or replace function public.admin_set_feature_flag(p_id uuid,p_enabled boolean,p_reason text) returns jsonb language plpgsql security definer set search_path=public as $$ declare o jsonb;n jsonb;begin if not public.has_admin_permission('platform.manage') then raise exception 'platform.manage permission required';end if;if trim(coalesce(p_reason,''))='' then raise exception 'Reason is required';end if;select to_jsonb(x) into o from public.platform_feature_flags x where id=p_id;update public.platform_feature_flags set enabled=p_enabled,updated_at=now() where id=p_id returning to_jsonb(platform_feature_flags) into n;perform public.admin_append_audit('FEATURE_FLAG_UPDATED','platform_feature_flag',p_id,o,n,p_reason);return n;end $$;

create or replace function public.admin_touch_platform_integration(p_id uuid,p_reason text) returns jsonb language plpgsql security definer set search_path=public as $$ declare o jsonb;n jsonb;begin if not public.has_admin_permission('platform.manage') then raise exception 'platform.manage permission required';end if;if trim(coalesce(p_reason,''))='' then raise exception 'Reason is required';end if;select to_jsonb(x) into o from public.platform_integrations x where id=p_id;update public.platform_integrations set last_checked_at=now() where id=p_id returning to_jsonb(platform_integrations) into n;perform public.admin_append_audit('PLATFORM_INTEGRATION_CHECKED','platform_integration',p_id,o,n,p_reason);return n;end $$;

-- Plan/offer RPCs encapsulate parent and child-row writes in one transaction.
create or replace function public.admin_save_subscription_plan(p_id uuid,p_payload jsonb,p_modules jsonb,p_reason text) returns jsonb language plpgsql security definer set search_path=public as $$ declare o jsonb;n jsonb;v_id uuid;begin if not public.has_admin_permission('subscriptions.manage') then raise exception 'subscriptions.manage permission required';end if;if trim(coalesce(p_reason,''))='' then raise exception 'Reason is required';end if;if p_id is null then insert into public.subscription_plans(code,name,monthly_price,annual_price,currency_code,billing_model,setup_fee,trial_days,minimum_seats,included_seats,overage_enabled,overage_config,is_featured,public_visible,display_order,is_active,description,limits,features) values(p_payload->>'code',p_payload->>'name',(p_payload->>'monthly_price')::numeric,(p_payload->>'annual_price')::numeric,p_payload->>'currency_code',p_payload->>'billing_model',(p_payload->>'setup_fee')::numeric,(p_payload->>'trial_days')::int,(p_payload->>'minimum_seats')::int,(p_payload->>'included_seats')::int,(p_payload->>'overage_enabled')::boolean,p_payload->'overage_config',(p_payload->>'is_featured')::boolean,(p_payload->>'public_visible')::boolean,(p_payload->>'display_order')::int,(p_payload->>'is_active')::boolean,p_payload->>'description',p_payload->'limits',p_payload->'features') returning id,to_jsonb(subscription_plans) into v_id,n;else select to_jsonb(x) into o from public.subscription_plans x where id=p_id;update public.subscription_plans set code=p_payload->>'code',name=p_payload->>'name',monthly_price=(p_payload->>'monthly_price')::numeric,annual_price=(p_payload->>'annual_price')::numeric,currency_code=p_payload->>'currency_code',billing_model=p_payload->>'billing_model',setup_fee=(p_payload->>'setup_fee')::numeric,trial_days=(p_payload->>'trial_days')::int,minimum_seats=(p_payload->>'minimum_seats')::int,included_seats=(p_payload->>'included_seats')::int,overage_enabled=(p_payload->>'overage_enabled')::boolean,overage_config=p_payload->'overage_config',is_featured=(p_payload->>'is_featured')::boolean,public_visible=(p_payload->>'public_visible')::boolean,display_order=(p_payload->>'display_order')::int,is_active=(p_payload->>'is_active')::boolean,description=p_payload->>'description',limits=p_payload->'limits',features=p_payload->'features',updated_at=now() where id=p_id returning id,to_jsonb(subscription_plans) into v_id,n;end if;delete from public.subscription_plan_modules where plan_id=v_id;insert into public.subscription_plan_modules(plan_id,module_code,module_name,enabled,limit_value,limit_unit,notes) select v_id,x->>'module_code',x->>'module_name',(x->>'enabled')::boolean,(x->>'limit_value')::numeric,x->>'limit_unit',x->>'notes' from jsonb_array_elements(coalesce(p_modules,'[]'::jsonb)) x;perform public.admin_append_audit(case when o is null then 'SUBSCRIPTION_PLAN_CREATED' else 'SUBSCRIPTION_PLAN_UPDATED' end,'subscription_plan',v_id,o,n,p_reason);return n;end $$;

create or replace function public.admin_save_subscription_offer(p_id uuid,p_payload jsonb,p_plan_ids uuid[],p_reason text) returns jsonb language plpgsql security definer set search_path=public as $$ declare o jsonb;n jsonb;v_id uuid;begin if not public.has_admin_permission('subscriptions.manage') then raise exception 'subscriptions.manage permission required';end if;if trim(coalesce(p_reason,''))='' then raise exception 'Reason is required';end if;if p_id is null then insert into public.subscription_offers(code,name,description,offer_type,discount_type,discount_value,buy_quantity,free_quantity,trial_days,credit_amount,starts_at,ends_at,max_redemptions,max_redemptions_per_customer,first_time_only,auto_apply,stackable,is_active) values(p_payload->>'code',p_payload->>'name',p_payload->>'description',p_payload->>'offer_type',p_payload->>'discount_type',(p_payload->>'discount_value')::numeric,(p_payload->>'buy_quantity')::int,(p_payload->>'free_quantity')::int,(p_payload->>'trial_days')::int,(p_payload->>'credit_amount')::numeric,(p_payload->>'starts_at')::timestamptz,(p_payload->>'ends_at')::timestamptz,(p_payload->>'max_redemptions')::int,(p_payload->>'max_redemptions_per_customer')::int,(p_payload->>'first_time_only')::boolean,(p_payload->>'auto_apply')::boolean,(p_payload->>'stackable')::boolean,(p_payload->>'is_active')::boolean) returning id,to_jsonb(subscription_offers) into v_id,n;else select to_jsonb(x) into o from public.subscription_offers x where id=p_id;update public.subscription_offers set code=p_payload->>'code',name=p_payload->>'name',description=p_payload->>'description',offer_type=p_payload->>'offer_type',discount_type=p_payload->>'discount_type',discount_value=(p_payload->>'discount_value')::numeric,buy_quantity=(p_payload->>'buy_quantity')::int,free_quantity=(p_payload->>'free_quantity')::int,trial_days=(p_payload->>'trial_days')::int,credit_amount=(p_payload->>'credit_amount')::numeric,starts_at=(p_payload->>'starts_at')::timestamptz,ends_at=(p_payload->>'ends_at')::timestamptz,max_redemptions=(p_payload->>'max_redemptions')::int,max_redemptions_per_customer=(p_payload->>'max_redemptions_per_customer')::int,first_time_only=(p_payload->>'first_time_only')::boolean,auto_apply=(p_payload->>'auto_apply')::boolean,stackable=(p_payload->>'stackable')::boolean,is_active=(p_payload->>'is_active')::boolean,updated_at=now() where id=p_id returning id,to_jsonb(subscription_offers) into v_id,n;end if;delete from public.subscription_offer_plans where offer_id=v_id;insert into public.subscription_offer_plans(offer_id,plan_id) select v_id,unnest(coalesce(p_plan_ids,array[]::uuid[]));perform public.admin_append_audit(case when o is null then 'SUBSCRIPTION_OFFER_CREATED' else 'SUBSCRIPTION_OFFER_UPDATED' end,'subscription_offer',v_id,o,n,p_reason);return n;end $$;

drop policy if exists billing_company_admin_all on public.billing_company_profile;
drop policy if exists billing_payment_methods_admin_all on public.billing_payment_methods;
create policy billing_company_select on public.billing_company_profile for select to authenticated using (public.has_admin_permission('payments.view') or public.has_admin_permission('payments.manage'));
create policy billing_payment_methods_select on public.billing_payment_methods for select to authenticated using (public.has_admin_permission('payments.view') or public.has_admin_permission('payments.manage'));
revoke insert,update,delete,truncate,references,trigger on public.billing_company_profile,public.billing_payment_methods from anon,authenticated;

revoke execute on function public.admin_update_billing_company_profile(uuid,jsonb,text),public.admin_upsert_payment_method(uuid,jsonb,text),public.admin_update_subscription_billing_settings(uuid,jsonb,text),public.admin_update_business_subscription(uuid,jsonb,text),public.admin_update_platform_setting(uuid,jsonb,text),public.admin_set_feature_flag(uuid,boolean,text),public.admin_touch_platform_integration(uuid,text),public.admin_save_subscription_plan(uuid,jsonb,jsonb,text),public.admin_save_subscription_offer(uuid,jsonb,uuid[],text) from public,anon;
grant execute on function public.admin_update_billing_company_profile(uuid,jsonb,text),public.admin_upsert_payment_method(uuid,jsonb,text),public.admin_update_subscription_billing_settings(uuid,jsonb,text),public.admin_update_business_subscription(uuid,jsonb,text),public.admin_update_platform_setting(uuid,jsonb,text),public.admin_set_feature_flag(uuid,boolean,text),public.admin_touch_platform_integration(uuid,text),public.admin_save_subscription_plan(uuid,jsonb,jsonb,text),public.admin_save_subscription_offer(uuid,jsonb,uuid[],text) to authenticated;
commit;